"""Net2Net weight transplant: Unitree-Go2-LongJump-Base-v1 (Stage A) actor/critic
weights -> a freshly-constructed Unitree-Go2-LongJump-v1 (Stage B, ActorCriticEE) policy.

See リファレンス_ExplicitEstimator実装仕様.md / リファレンス_キーボード操作とNet2Net設計の下調べ.md
for the design this implements. Summary of what gets transplanted vs. not:

- critic.*                : copied 1:1 (Stage A and Stage B share the exact
                             same CriticCfg -- longjump_env_cfg.py only adds
                             a new "estimator_target" *group*, it does not
                             touch "critic").
- std / log_std           : copied 1:1 (same num_actions, unaffected by the
                             observation change).
- actor.<last few>.*      : copied 1:1 (every layer except the first is
                             architecturally unchanged -- only the INPUT
                             width grows).
- actor.0.weight          : Net2Net-style column surgery. Stage B's actor
                             input is [stage_a_policy_obs (45),
                             jump_command (1, NEW), estimator_output (41,
                             NEW)] = 87 columns; see longjump_env_cfg.py's
                             PolicyCfgLongJump for why jump_command lands
                             immediately after the inherited 45 (Python
                             dataclass inheritance appends new fields after
                             the parent's). The first 45 columns are copied
                             from Stage A's actor.0.weight; the remaining 42
                             (jump_command + all 41 estimator outputs) are
                             zero-initialized so that, at the moment of
                             transplant and with jump_command==0, the new
                             actor computes *exactly* the same function
                             Stage A learned, regardless of the untrained
                             estimator's (effectively garbage) output --
                             that zero-column cancels it out. This is the
                             textbook Net2Net "widen, preserve function"
                             property.
- actor.0.bias            : copied 1:1 (output width of layer 0 is
                             unchanged; only its input width grew).
- estimator.*             : left at its fresh random initialization --
                             there is no Stage-A analog to transplant from.
- actor_obs_normalizer / critic_obs_normalizer:
                             both stages train with normalization off
                             (confirmed empty actor_obs_normalization /
                             critic_obs_normalization in agent.yaml), so
                             these are stateless nn.Identity() on both
                             sides -- nothing to transplant.
- PPOEE.optimizer / estimator_optimizer:
                             NOT transplanted -- rebuilt fresh (see below).

KNOWN GAP (flagged, not solved here): rsl_rl's OnPolicyRunner.save()/load()
only knows about a single ``self.alg.optimizer``; it has no concept of
PPOEE's second ``estimator_optimizer``. This script's output checkpoint
still round-trips correctly through the normal --resume flow for the *main*
PPO optimizer (a freshly-initialized Adam state, which is generated by
briefly constructing a PPOEE around the transplanted policy purely to get a
correctly-shaped state dict from the right parameter groups). The
estimator_optimizer will simply reinitialize with default Adam state the
first time PPOEE.__init__() runs on this checkpoint's task -- immaterial
for a from-scratch estimator (nothing meaningful to preserve there anyway),
but worth knowing if this pattern is reused for other resume scenarios.

Usage:
    python scripts/rsl_rl/longjump_net2net_transplant.py \\
        --stage_a_checkpoint logs/rsl_rl/unitree_go2_longjump_base_v1/<run>/model_<N>.pt \\
        --output_dir logs/rsl_rl/unitree_go2_longjump_v1/<new_run>_net2net

Then resume Stage B training from it:
    python scripts/rsl_rl/train.py --task Unitree-Go2-LongJump-v1 \\
        --resume --load_run <new_run>_net2net --checkpoint model_0.pt
"""

import argparse
import os

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--stage_a_checkpoint", type=str, required=True, help="Path to a Stage A (LongJump-Base) .pt file.")
# 2026-09-13: the Stage B config used to be hard-coded to Go2's. Porting the task to
# Anaguma broke on it -- the Estimator's regression target includes one entry per link
# (mdp.link_contact_bool), and the two machines do not have the same number of links, so
# the transplanted checkpoint came out 4 wide and train.py refused it:
#   size mismatch for actor.0.weight: checkpoint [512, 88] vs model [512, 84]
# The Stage A side needs no such argument: its dimensions are read off the checkpoint's
# own tensor shapes, never from a config.
parser.add_argument(
    "--stage_b_cfg",
    type=str,
    default="unitree_rl_lab.tasks.locomotion.robots.go2.longjump_env_cfg:RobotEnvCfgLongJump",
    help="module:ClassName of the Stage B env cfg to size the new policy against.",
)
parser.add_argument(
    "--output_dir",
    type=str,
    required=True,
    help="Directory to write the transplanted Stage B checkpoint into (as model_0.pt), matching the"
    " logs/rsl_rl/<experiment_name>/<run_name>/ layout --load_run/--checkpoint expect.",
)
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

"""Rest everything follows (needs the simulation app running first)."""

import torch  # noqa: E402

from isaaclab.envs import ManagerBasedRLEnv  # noqa: E402

import unitree_rl_lab.tasks  # noqa: F401, E402 (registers gym tasks + injects ActorCriticEE/PPOEE)
from unitree_rl_lab.tasks.locomotion.agents.rsl_rl_ee import ActorCriticEE, PPOEE  # noqa: E402
from unitree_rl_lab.tasks.locomotion.agents.rsl_rl_ppo_cfg import LongJumpPPORunnerCfg  # noqa: E402
from unitree_rl_lab.tasks.locomotion.robots.go2.longjump_env_cfg import RobotEnvCfgLongJump  # noqa: E402


def build_policy(env_cfg_cls, runner_cfg, policy_cls, obs_groups):
    """Instantiate `policy_cls` (ActorCritic or ActorCriticEE) sized for `env_cfg_cls`'s env.

    ``obs_groups`` is passed explicitly rather than read off ``runner_cfg``:
    outside the normal train.py/OnPolicyRunner flow, ``RslRlOnPolicyRunnerCfg.obs_groups``
    is still its unresolved ``MISSING`` sentinel (the auto-default-filling
    that ``rsl_rl.utils.resolve_obs_groups`` normally does happens inside
    ``OnPolicyRunner.__init__``, which this script never constructs).

    Only ever called ONCE per process, for Stage B: constructing two
    ManagerBasedRLEnv instances (Stage A's and Stage B's) back to back in
    the same process was tried first and hit a RecursionError inside
    isaaclab's configclass validation (some shared/mutated class-level
    config object, e.g. COBBLESTONE_ROAD_CFG, going circular on the second
    construction) -- so Stage A's dimensions are instead read directly off
    its checkpoint's tensor shapes (see ``main()``), with no live env needed
    for it at all.
    """
    cfg = env_cfg_cls()
    cfg.scene.num_envs = 1
    env = ManagerBasedRLEnv(cfg=cfg)
    obs, _ = env.reset()
    policy_kwargs = runner_cfg.policy.to_dict()
    policy_kwargs.pop("class_name")
    policy = policy_cls(obs, obs_groups, env.action_manager.total_action_dim, **policy_kwargs)
    return policy, env


def main():
    stage_a_state = torch.load(args_cli.stage_a_checkpoint, weights_only=False)["model_state_dict"]
    print(f"[INFO] Loaded Stage A checkpoint from {args_cli.stage_a_checkpoint}.")
    num_stage_a_actor_obs = stage_a_state["actor.0.weight"].shape[1]

    import importlib

    _mod, _cls = args_cli.stage_b_cfg.split(":")
    stage_b_cfg_cls = getattr(importlib.import_module(_mod), _cls)
    print(f"[INFO] Building Stage B ({stage_b_cfg_cls.__name__}) policy (fresh init)...")
    stage_b_runner_cfg = LongJumpPPORunnerCfg()
    stage_b_policy, stage_b_env = build_policy(
        stage_b_cfg_cls, stage_b_runner_cfg, ActorCriticEE, stage_b_runner_cfg.obs_groups
    )

    # --- 1:1 copies (critic is architecturally identical between stages: ---
    # --- longjump_env_cfg.py only adds the new "estimator_target" *group*, ---
    # --- it does not touch CriticCfg) ---
    critic_state = {k[len("critic."):]: v for k, v in stage_a_state.items() if k.startswith("critic.")}
    stage_b_policy.critic.load_state_dict(critic_state)
    if "std" in stage_a_state:
        stage_b_policy.std.data.copy_(stage_a_state["std"])
    elif "log_std" in stage_a_state:
        stage_b_policy.log_std.data.copy_(stage_a_state["log_std"])

    # --- Net2Net surgery on the actor's first layer ---
    stage_b_first = stage_b_policy.actor[0]
    assert stage_b_first.in_features > num_stage_a_actor_obs, (
        "Stage B's actor input must be wider than Stage A's (jump_command + estimator output added);"
        f" got stage_a={num_stage_a_actor_obs}, stage_b={stage_b_first.in_features}."
    )
    with torch.no_grad():
        stage_b_first.weight.zero_()
        stage_b_first.weight[:, :num_stage_a_actor_obs].copy_(stage_a_state["actor.0.weight"])
        stage_b_first.bias.copy_(stage_a_state["actor.0.bias"])

    # --- Every other actor layer is architecturally unchanged: copy 1:1 ---
    stage_a_actor_layer_indices = sorted(
        {int(k.split(".")[1]) for k in stage_a_state if k.startswith("actor.")} - {0}
    )
    for i in stage_a_actor_layer_indices:
        stage_b_policy.actor[i].weight.data.copy_(stage_a_state[f"actor.{i}.weight"])
        stage_b_policy.actor[i].bias.data.copy_(stage_a_state[f"actor.{i}.bias"])

    print(
        f"[INFO] Net2Net surgery done: copied columns [0:{num_stage_a_actor_obs}] of actor.0, zeroed columns"
        f" [{num_stage_a_actor_obs}:{stage_b_first.in_features}] (jump_command + estimator output)."
        " estimator.* left at random init (no Stage A analog)."
    )

    # --- Fresh optimizer state for the transplanted policy (see module docstring: the ---
    # --- estimator_optimizer is a known gap in rsl_rl's save/load, not addressed here). ---
    ppoee = PPOEE(
        stage_b_policy,
        estimator_lr=stage_b_runner_cfg.algorithm.estimator_lr,
        num_learning_epochs=stage_b_runner_cfg.algorithm.num_learning_epochs,
        num_mini_batches=stage_b_runner_cfg.algorithm.num_mini_batches,
        clip_param=stage_b_runner_cfg.algorithm.clip_param,
        gamma=stage_b_runner_cfg.algorithm.gamma,
        lam=stage_b_runner_cfg.algorithm.lam,
        value_loss_coef=stage_b_runner_cfg.algorithm.value_loss_coef,
        entropy_coef=stage_b_runner_cfg.algorithm.entropy_coef,
        learning_rate=stage_b_runner_cfg.algorithm.learning_rate,
        max_grad_norm=stage_b_runner_cfg.algorithm.max_grad_norm,
        use_clipped_value_loss=stage_b_runner_cfg.algorithm.use_clipped_value_loss,
        schedule=stage_b_runner_cfg.algorithm.schedule,
        desired_kl=stage_b_runner_cfg.algorithm.desired_kl,
        device=stage_b_env.device,
    )

    os.makedirs(args_cli.output_dir, exist_ok=True)
    out_path = os.path.join(args_cli.output_dir, "model_0.pt")
    torch.save(
        {
            "model_state_dict": stage_b_policy.state_dict(),
            "optimizer_state_dict": ppoee.optimizer.state_dict(),
            "iter": 0,
            "infos": {"net2net_transplant_from": args_cli.stage_a_checkpoint},
        },
        out_path,
    )
    print(f"[INFO] Wrote transplanted Stage B checkpoint to {out_path}")
    print(
        "[INFO] Resume Stage B training with:\n"
        f"    python scripts/rsl_rl/train.py --task Unitree-Go2-LongJump-v1 --resume"
        f" --load_run {os.path.basename(args_cli.output_dir)} --checkpoint model_0.pt"
    )


if __name__ == "__main__":
    main()
    simulation_app.close()
