"""The wire format between the model and the robot -- written, read and constrained in one place.

The model does not emit JSON. It emits a spoken reply, a blank line, then the program:

    了解、5m進んでからバク転するね。

    program: [{"skill": "move", "dir": "forward", "speed": "normal", "distance_m": 5.0}, ...]

Keeping the reply outside the JSON is what lets a 1.7B model write natural Japanese: quotes,
brackets and long vowels in the reply can no longer break an escape sequence, and only the part
that is genuinely machine-shaped has to be valid JSON.

Four things have to agree on that format -- the training script that writes the target text, the
evaluation script that reads a generation back, the robot client that does the same, and the GBNF
grammar llama.cpp constrains sampling with. They agree because they all call this module. A format
mismatch between any two of them would show up as "the parse occasionally fails", which is the kind
of bug that is noticed late and debugged slowly.

The step vocabulary itself is not restated here: ``dir``/``speed``/``kind`` and the field order come
from ``unitree_rl_lab.program.grammar``, so adding a skill updates the prompt, the grammar and the
parser together.

    python scripts/llm/chat_format.py                       # show a rendered example and the GBNF
    python scripts/llm/chat_format.py --check data/llm/dataset.jsonl   # render/parse every row
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from unitree_rl_lab.program.grammar import DIRECTIONS, FLIP_KINDS, SPEEDS, STANCE_KINDS, TURN_DIRECTIONS
except ModuleNotFoundError:  # the fine-tuning venv has no Isaac Lab install; the package is pure Python
    sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "source" / "unitree_rl_lab"))
    from unitree_rl_lab.program.grammar import DIRECTIONS, FLIP_KINDS, SPEEDS, STANCE_KINDS, TURN_DIRECTIONS

# What the model is trained to write. The reply is one line, so the separator is unambiguous.
SEPARATOR = "\n\nprogram: "

# What the model is allowed to have written. Slightly looser than SEPARATOR -- a generation that
# lands on "program:" without the space, or with a stray blank line, is a formatting slip and not a
# failure to understand the instruction, so it is read rather than thrown away.
_SEPARATOR_RE = re.compile(r"\n\s*program\s*:\s*")


class FormatError(ValueError):
    """A generation that does not carry a readable reply and program."""


def render_output(reply: str, program: list[dict]) -> str:
    """The assistant text for one dataset row: the training target, and what the robot will read."""
    if "\n" in reply:
        raise FormatError(f"a reply must be one line, got {reply!r}")
    return reply + SEPARATOR + json.dumps(program, ensure_ascii=False)


def parse_output(text: str) -> tuple[str, list[dict]]:
    """Read a generation back. Raises :class:`FormatError` with the reason, for the eval to count."""
    matches = list(_SEPARATOR_RE.finditer(text))
    if not matches:
        raise FormatError("no 'program:' line")
    last = matches[-1]  # the reply is free text; only the final separator can be the real one
    reply = text[: last.start()].strip()
    body = text[last.end() :].strip()
    if not body.startswith("["):
        raise FormatError(f"program is not a list: {body[:40]!r}")
    try:
        program = json.loads(body)
    except json.JSONDecodeError as exc:
        raise FormatError(f"program is not valid JSON: {exc}") from exc
    if not isinstance(program, list) or not all(isinstance(step, dict) for step in program):
        raise FormatError("program must be a list of objects")
    return reply, program


# --- GBNF -------------------------------------------------------------------------------------
#
# llama.cpp rejects any token that cannot continue a string this grammar accepts, so a constrained
# generation cannot produce an unknown direction, a missing field or a truncated list -- whatever
# the model's own probabilities say. The field order below is the order `step_to_dict` writes, and
# the check at the bottom of this file is what keeps the two in step.


def _alt(values) -> str:
    return " | ".join(f'"{value}"' for value in values)


def gbnf_grammar() -> str:
    """A GBNF grammar for the whole output, built from the same vocabulary the prompt describes."""
    return f'''# Generated by scripts/llm/chat_format.py -- do not edit by hand.
root       ::= reply "\\n\\nprogram: " program
reply      ::= [^\\n]+
program    ::= "[]" | "[" step (", " step)* "]"
step       ::= move | turn | stop | flip | stance

move       ::= "{{\\"skill\\": \\"move\\", \\"dir\\": \\"" dir "\\", \\"speed\\": \\"" speed "\\", " move-len "}}"
move-len   ::= "\\"duration_s\\": " num | "\\"distance_m\\": " num
turn       ::= "{{\\"skill\\": \\"turn\\", \\"dir\\": \\"" turn-dir "\\", \\"speed\\": \\"" speed "\\", " turn-len "}}"
turn-len   ::= "\\"duration_s\\": " num | "\\"angle_deg\\": " num
stop       ::= "{{\\"skill\\": \\"stop\\", \\"duration_s\\": " num "}}"
flip       ::= "{{\\"skill\\": \\"flip\\", \\"kind\\": \\"" flip-kind "\\", \\"count\\": " int "}}"
stance     ::= "{{\\"skill\\": \\"stance\\", \\"kind\\": \\"" stance-kind "\\", \\"duration_s\\": " num stance-dir ", \\"speed\\": \\"" speed "\\"}}"
stance-dir ::= (", \\"dir\\": \\"" dir "\\"")?

dir        ::= {_alt(DIRECTIONS)}
turn-dir   ::= {_alt(TURN_DIRECTIONS)}
speed      ::= {_alt(SPEEDS)}
flip-kind  ::= {_alt(FLIP_KINDS)}
stance-kind ::= {_alt(STANCE_KINDS)}
num        ::= [0-9]+ ("." [0-9]+)?
int        ::= [0-9]+
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", metavar="DATASET", help="render and re-read every row of a dataset")
    parser.add_argument("--gbnf", metavar="PATH", help="write the grammar to a file")
    args = parser.parse_args()

    if args.gbnf:
        Path(args.gbnf).write_text(gbnf_grammar())
        print(f"wrote {args.gbnf}")
        return

    if not args.check:
        example = ("了解、5m進んでからバク転するね。",
                   [{"skill": "move", "dir": "forward", "speed": "normal", "distance_m": 5.0},
                    {"skill": "flip", "kind": "backflip", "count": 1}])
        print(render_output(*example))
        print("\n--- GBNF ---")
        print(gbnf_grammar())
        return

    total = failed = 0
    for line in open(args.check):
        row = json.loads(line)
        total += 1
        text = render_output(row["output"]["reply"], row["output"]["program"])
        try:
            reply, program = parse_output(text)
        except FormatError as exc:
            print(f"  FAIL {row['id']}: {exc}")
            failed += 1
            continue
        if reply != row["output"]["reply"] or program != row["output"]["program"]:
            print(f"  FAIL {row['id']}: round-trip changed the content")
            failed += 1
    print(f"{total - failed}/{total} rows render and read back unchanged")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
