# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Lee et al. 2020 student distillation: behavior cloning + latent matching."""

from __future__ import annotations

import torch.nn as nn

from rsl_rl.algorithms import Distillation as RslDistillation
from rsl_rl.storage import RolloutStorage
from rsl_rl.utils import resolve_optimizer

from unitree_rl_lab.assets.models.modules.student_teacher import TcnStudentTeacher


class TcnDistillation(RslDistillation):
    """Distillation with the paper's student loss (Eq. 1).

    Named ``TcnDistillation`` so rsl-rl's default ``Distillation`` class_name
    still resolves to the stock algorithm. Builds one optimizer over student
    parameters only (frozen teacher weights are excluded).

        L = L_bc + latent_loss_coef * L_latent

    ``L_bc`` is MSE between student and teacher actions. ``L_latent`` is MSE
    between the TCN embedding ``l_t`` and the teacher's privileged embedding
    ``l̄_t``. Rollouts are generated by the student (DAgger).
    """

    policy: TcnStudentTeacher

    def __init__(
        self,
        policy: TcnStudentTeacher,
        num_learning_epochs: int = 1,
        gradient_length: int = 15,
        learning_rate: float = 1e-3,
        max_grad_norm: float | None = None,
        loss_type: str = "mse",
        optimizer: str = "adam",
        device: str = "cpu",
        multi_gpu_cfg: dict | None = None,
        latent_loss_coef: float = 1.0,
        weight_decay: float = 1.0e-4,
    ) -> None:
        self.device = device
        self.is_multi_gpu = multi_gpu_cfg is not None
        if multi_gpu_cfg is not None:
            self.gpu_global_rank = multi_gpu_cfg["global_rank"]
            self.gpu_world_size = multi_gpu_cfg["world_size"]
        else:
            self.gpu_global_rank = 0
            self.gpu_world_size = 1

        self.policy = policy
        self.policy.to(self.device)
        self.storage = None
        student_params = [
            param
            for name, param in self.policy.named_parameters()
            if param.requires_grad and not name.startswith("teacher")
        ]
        self.optimizer = resolve_optimizer(optimizer)(
            student_params, lr=learning_rate, weight_decay=weight_decay
        )
        self.transition = RolloutStorage.Transition()
        self.last_hidden_states = (None, None)
        self.num_learning_epochs = num_learning_epochs
        self.gradient_length = gradient_length
        self.learning_rate = learning_rate
        self.max_grad_norm = max_grad_norm
        loss_fn_dict = {
            "mse": nn.functional.mse_loss,
            "huber": nn.functional.huber_loss,
        }
        if loss_type not in loss_fn_dict:
            raise ValueError(f"Unknown loss type: {loss_type}. Supported types are: {list(loss_fn_dict.keys())}")
        self.loss_fn = loss_fn_dict[loss_type]
        self.num_updates = 0
        self.latent_loss_coef = latent_loss_coef

    def update(self) -> dict[str, float]:
        self.num_updates += 1
        mean_behavior_loss = 0.0
        mean_latent_loss = 0.0
        loss = 0
        cnt = 0

        for _ in range(self.num_learning_epochs):
            self.policy.reset(hidden_states=self.last_hidden_states)
            self.policy.detach_hidden_states()
            for obs, _, privileged_actions, dones in self.storage.generator():
                actions, student_latent = self.policy.act_inference(obs, return_latent=True)
                teacher_latent = self.policy.evaluate_latent(obs)

                behavior_loss = self.loss_fn(actions, privileged_actions)
                latent_loss = self.loss_fn(student_latent, teacher_latent)
                step_loss = behavior_loss + self.latent_loss_coef * latent_loss

                loss = loss + step_loss
                mean_behavior_loss += behavior_loss.item()
                mean_latent_loss += latent_loss.item()
                cnt += 1

                if cnt % self.gradient_length == 0:
                    self.optimizer.zero_grad()
                    loss.backward()
                    if self.is_multi_gpu:
                        self.reduce_parameters()
                    if self.max_grad_norm:
                        nn.utils.clip_grad_norm_(
                            [
                                param
                                for name, param in self.policy.named_parameters()
                                if param.requires_grad and not name.startswith("teacher")
                            ],
                            self.max_grad_norm,
                        )
                    self.optimizer.step()
                    self.policy.detach_hidden_states()
                    loss = 0

                self.policy.reset(dones.view(-1))
                self.policy.detach_hidden_states(dones.view(-1))

        mean_behavior_loss /= cnt
        mean_latent_loss /= cnt
        self.storage.clear()
        self.last_hidden_states = self.policy.get_hidden_states()
        self.policy.detach_hidden_states()

        return {
            "behavior": mean_behavior_loss,
            "latent": mean_latent_loss,
            "total": mean_behavior_loss + self.latent_loss_coef * mean_latent_loss,
        }
