"""Lee et al. 2020 student distillation: behavior cloning + latent matching."""

from __future__ import annotations

import torch.nn as nn

from rsl_rl.algorithms import Distillation as RslDistillation
from rsl_rl.modules import StudentTeacher, StudentTeacherRecurrent
from rsl_rl.utils import resolve_optimizer


class Distillation(RslDistillation):
    """Distillation with the paper's student loss (Eq. 1).

    Extends ``rsl_rl.algorithms.Distillation``. Parent handles rollout
    collection, storage, and multi-GPU sync. ``update()`` is overridden:

        L = L_bc + latent_loss_coef * L_latent

    ``L_bc`` is MSE between student and teacher actions. ``L_latent`` is MSE
    between the TCN embedding ``l_t`` and the teacher's privileged embedding
    ``l̄_t``. Rollouts are generated by the student (DAgger).
    """

    policy: StudentTeacher | StudentTeacherRecurrent

    def __init__(
        self,
        policy: StudentTeacher | StudentTeacherRecurrent,
        num_learning_epochs: int = 1,
        gradient_length: int = 15,
        learning_rate: float = 1e-3,
        max_grad_norm: float | None = None,
        loss_type: str = "mse",
        optimizer: str = "adam",
        device: str = "cpu",
        multi_gpu_cfg: dict | None = None,
        latent_loss_coef: float = 1.0,
        weight_decay: float = 1.0e-4,
    ) -> None:
        super().__init__(
            policy,
            num_learning_epochs=num_learning_epochs,
            gradient_length=gradient_length,
            learning_rate=learning_rate,
            max_grad_norm=max_grad_norm,
            loss_type=loss_type,
            optimizer=optimizer,
            device=device,
            multi_gpu_cfg=multi_gpu_cfg,
        )
        self.latent_loss_coef = latent_loss_coef
        student_params = [
            param
            for name, param in self.policy.named_parameters()
            if param.requires_grad and not name.startswith("teacher")
        ]
        self.optimizer = resolve_optimizer(optimizer)(
            student_params, lr=learning_rate, weight_decay=weight_decay
        )

    def update(self) -> dict[str, float]:
        self.num_updates += 1
        mean_behavior_loss = 0.0
        mean_latent_loss = 0.0
        loss = 0
        cnt = 0

        for _ in range(self.num_learning_epochs):
            self.policy.reset(hidden_states=self.last_hidden_states)
            self.policy.detach_hidden_states()
            for obs, _, privileged_actions, dones in self.storage.generator():
                actions, student_latent = self.policy.act_inference(obs, return_latent=True)
                teacher_latent = self.policy.evaluate_latent(obs)

                behavior_loss = self.loss_fn(actions, privileged_actions)
                latent_loss = self.loss_fn(student_latent, teacher_latent)
                step_loss = behavior_loss + self.latent_loss_coef * latent_loss

                loss = loss + step_loss
                mean_behavior_loss += behavior_loss.item()
                mean_latent_loss += latent_loss.item()
                cnt += 1

                if cnt % self.gradient_length == 0:
                    self.optimizer.zero_grad()
                    loss.backward()
                    if self.is_multi_gpu:
                        self.reduce_parameters()
                    if self.max_grad_norm:
                        nn.utils.clip_grad_norm_(
                            [
                                param
                                for name, param in self.policy.named_parameters()
                                if param.requires_grad and not name.startswith("teacher")
                            ],
                            self.max_grad_norm,
                        )
                    self.optimizer.step()
                    self.policy.detach_hidden_states()
                    loss = 0

                self.policy.reset(dones.view(-1))
                self.policy.detach_hidden_states(dones.view(-1))

        mean_behavior_loss /= cnt
        mean_latent_loss /= cnt
        self.storage.clear()
        self.last_hidden_states = self.policy.get_hidden_states()
        self.policy.detach_hidden_states()

        return {
            "behavior": mean_behavior_loss,
            "latent": mean_latent_loss,
            "total": mean_behavior_loss + self.latent_loss_coef * mean_latent_loss,
        }
