#include "FSM/State_RLBase.h"
#include "unitree_articulation.h"
#include "isaaclab/envs/manager_based_rl_env.h"
#include "isaaclab/envs/mdp/observations/observations.h"
#include "isaaclab/envs/mdp/actions/joint_actions.h"

#include <array>
#include <algorithm>
#include <cmath>
#include <ctime>
#include <fstream>
#include <optional>
#include <string>
#include <vector>

namespace isaaclab
{

// Keyboard driving of a velocity policy. Two knobs, resolved in this order (first hit wins):
//
//   1. config.yaml   FSM/<state>/keyboard_vel_scale, keyboard_alpha
//   2. deploy.yaml   commands.base_velocity.{keyboard_vel_scale,keyboard_alpha}
//   3. built-in      0.8 and 0.15
//
// config.yaml comes first because it is the hand-maintained operator config, while deploy.yaml is
// regenerated by every training export -- an override written there is per-checkpoint and is lost
// the next time the policy is exported.
//
// vel_scale multiplies the exported command range, so 0.8 with a range of [0, 6] presses F for
// 4.8 m/s. That default is deliberate headroom for steering and for policies whose top range entry
// is beyond what they can hold; set it to 1.0 when the point of the run is to measure the ceiling.
//
// deploy.yaml also has to name this term instead of the plain one:
//   observations: keyboard_velocity_commands  (not velocity_commands)

// Latched keyboard velocity command. Lifted out of keyboard_velocity_commands (where it was a
// function-local static) so the speed capture further down can record what was ASKED for next to
// what the robot did -- a torque trace is not interpretable without knowing the command that
// produced it. Same lifetime and semantics as before.
std::array<float, 3> g_keyboard_cmd = {0.0f, 0.0f, 0.0f};

// Set from config.yaml by the State_RLBase constructor; unset means "fall through to deploy.yaml".
std::optional<float> g_keyboard_vel_scale;
std::optional<float> g_keyboard_alpha;

REGISTER_OBSERVATION(keyboard_velocity_commands)
{
    if (!FSMState::keyboard)
    {
        FSMState::keyboard = std::make_shared<Keyboard>();
    }

    auto keyboard = FSMState::keyboard;
    const auto cmd_cfg = env->cfg["commands"]["base_velocity"];
    const auto ranges = cmd_cfg["ranges"];

    float vel_scale = 0.8f;
    if (cmd_cfg["keyboard_vel_scale"].IsDefined())
    {
        vel_scale = cmd_cfg["keyboard_vel_scale"].as<float>();
    }
    if (g_keyboard_vel_scale)
    {
        vel_scale = *g_keyboard_vel_scale;
    }

    float alpha = 0.15f;
    if (cmd_cfg["keyboard_alpha"].IsDefined())
    {
        alpha = cmd_cfg["keyboard_alpha"].as<float>();
    }
    if (g_keyboard_alpha)
    {
        alpha = *g_keyboard_alpha;
    }

    const auto sx = [&](int idx) { return vel_scale * ranges["lin_vel_x"][idx].as<float>(); };
    const auto sy = [&](int idx) { return vel_scale * ranges["lin_vel_y"][idx].as<float>(); };
    const auto sz = [&](int idx) { return vel_scale * ranges["ang_vel_z"][idx].as<float>(); };

    auto & cmd = g_keyboard_cmd;
    std::array<float, 3> target = {0.0f, 0.0f, 0.0f};

    if (keyboard->consume_velocity_stop())
    {
        cmd = {0.0f, 0.0f, 0.0f};
        return std::vector<float>(cmd.begin(), cmd.end());
    }

    if (keyboard->pressed("f"))
    {
        target[0] += sx(1);
    }
    if (keyboard->pressed("b"))
    {
        target[0] += sx(0);
    }
    if (keyboard->pressed("l"))
    {
        target[1] += sy(1);
    }
    if (keyboard->pressed("r"))
    {
        target[1] += sy(0);
    }
    if (keyboard->pressed("y"))
    {
        target[2] += sz(1);
    }
    if (keyboard->pressed("u"))
    {
        target[2] += sz(0);
    }

    for (int i = 0; i < 3; ++i)
    {
        cmd[i] = (1.0f - alpha) * cmd[i] + alpha * target[i];
    }

    cmd[0] = std::clamp(cmd[0], sx(0), sx(1));
    cmd[1] = std::clamp(cmd[1], sy(0), sy(1));
    cmd[2] = std::clamp(cmd[2], sz(0), sz(1));

    return std::vector<float>(cmd.begin(), cmd.end());
}

} // namespace isaaclab

namespace
{
// =================================================================================================
// 1 kHz speed / torque capture -- opt-in with `speed_log: true` under FSM/<state> in config.yaml.
//
// Answers the two questions a top-speed policy raises, which nothing in the 50 Hz policy loop can:
//
//   1. How fast did it actually go? The policy never observes its own linear velocity, and LowState
//      does not carry it either -- a real robot does not know its speed. unitree_mujoco does: go2.xml
//      declares `framelinvel name="frame_vel" objtype="site" objname="imu"` and the bridge copies it
//      into SportModeState::velocity, so this column is MuJoCo ground truth in simulation and stays
//      0 on hardware. World frame, so it is rotated into the body frame here with the IMU quaternion
//      to give a forward speed comparable to Isaac Lab's root_lin_vel_b[0].
//
//   2. Is each leg running out of torque? BOTH the commanded and the applied torque are recorded,
//      and that is the point. The applied value alone shows a joint pinned at its limit but not by
//      how far it is over: a controller asking for 24 N*m and one asking for 200 N*m produce
//      identical saturated traces, and the difference between them is exactly whether more torque
//      would buy more speed. tau_cmd is the same expression the MuJoCo bridge evaluates and the
//      motor firmware applies, so tau_cmd - tau_app is what the clamp threw away.
//      dq is recorded per joint because the limit is not a constant: Isaac Lab derates torque
//      linearly from X1 = 13.5 rad/s to zero at X2 = 30, and at 5 m/s roughly a quarter of the
//      thigh/calf steps sit inside that region. Utilisation has to be computed against the
//      speed-dependent envelope, not against the flat clamp.
//
// WINDOW: from the moment a forward command is latched (the `f` key) until the robot has stopped --
// command back to zero AND measured speed under `speed_log_stop_speed` for `speed_log_stop_hold_s`.
// A `speed_log_pre_s` pre-roll is kept so the standing start is visible, and `speed_log_max_s` caps
// a capture that never sees a stop. One CSV per run in the process CWD, named
// speed_<n>_YYYYMMDD-HHMMSS.csv, stamped at the trigger.
//
// Plot with scripts/plot_speed_capture.py.
// =================================================================================================

constexpr float kFsmDt = 0.001f;  // CtrlFSM::dt

// SDK motor order, matching UNITREE_GO2_CFG.joint_sdk_names. The plotting script classifies a
// column by its hip/thigh/calf suffix, so these names carry the torque limit with them.
const char * const kJointNames[12] = {
    "FR_hip", "FR_thigh", "FR_calf",
    "FL_hip", "FL_thigh", "FL_calf",
    "RR_hip", "RR_thigh", "RR_calf",
    "RL_hip", "RL_thigh", "RL_calf",
};

struct SpeedSample
{
    float t = 0.0f;  // seconds from the trigger; negative through the pre-roll
    float cmd_vx = 0.0f, cmd_vy = 0.0f, cmd_wz = 0.0f;
    float v_fwd = 0.0f;    // body-frame forward speed (ground truth, simulation only)
    float v_horiz = 0.0f;  // world-frame horizontal speed magnitude
    float v_world[3] = {0.0f, 0.0f, 0.0f};
    float base_z = 0.0f;
    float gravity_b[3] = {0.0f, 0.0f, 0.0f};
    float ang_vel_b[3] = {0.0f, 0.0f, 0.0f};
    float q[12] = {0.0f};
    float dq[12] = {0.0f};
    float tau_cmd[12] = {0.0f};
    float tau_app[12] = {0.0f};
};

class SpeedCapture
{
public:
    void configure(const YAML::Node & cfg, const std::string & state_string)
    {
        if (cfg["speed_log"])              enabled_     = cfg["speed_log"].as<bool>();
        if (cfg["speed_log_pre_s"])        pre_s_       = cfg["speed_log_pre_s"].as<float>();
        if (cfg["speed_log_max_s"])        max_s_       = cfg["speed_log_max_s"].as<float>();
        if (cfg["speed_log_stop_speed"])   stop_speed_  = cfg["speed_log_stop_speed"].as<float>();
        if (cfg["speed_log_stop_hold_s"])  stop_hold_s_ = cfg["speed_log_stop_hold_s"].as<float>();
        if (!enabled_) return;

        // Ground-truth base pose/velocity. Constructed regardless of who publishes, so the columns
        // exist either way; they simply stay 0 on hardware.
        highstate_ = std::make_shared<unitree::robot::go2::subscription::SportModeState>();
        pre_.assign(static_cast<size_t>(pre_s_ / kFsmDt) + 1u, SpeedSample{});
        spdlog::info(
            "State_{}: 1kHz speed capture ON -- speed_<n>_YYYYMMDD-HHMMSS.csv, pre-roll {:.2f}s, "
            "ends {:.2f}s after "
            "the command returns to zero with |v| < {:.2f} m/s (cap {:.1f}s)",
            state_string, pre_s_, stop_hold_s_, stop_speed_, max_s_);
    }

    void tick(isaaclab::ManagerBasedRLEnv * env)
    {
        if (!enabled_) return;

        SpeedSample s = sample(env);
        const bool commanded = isaaclab::g_keyboard_cmd[0] > trigger_cmd_;

        if (!capturing_)
        {
            pre_[pre_head_] = s;
            pre_head_ = (pre_head_ + 1u) % pre_.size();
            if (commanded) start();
            return;
        }

        s.t = elapsed_;
        samples_.push_back(s);
        elapsed_ += kFsmDt;

        // "Stopped" needs both halves: the command released AND the robot actually at rest. Either
        // alone ends the capture too early -- a released command still leaves several metres of
        // deceleration, which is part of the run.
        stop_held_ = (!commanded && s.v_horiz < stop_speed_) ? stop_held_ + kFsmDt : 0.0f;
        if (stop_held_ >= stop_hold_s_ || elapsed_ >= max_s_) write();
    }

private:
    void start()
    {
        capturing_ = true;
        elapsed_ = 0.0f;
        stop_held_ = 0.0f;
        samples_.clear();

        // Stamped at the trigger rather than at write time, so the file name says when the run
        // started. The index still leads the name: it keeps runs in order within a session even if
        // two land in the same second, and it is what the plots and notes have always referred to.
        const std::time_t now = std::time(nullptr);
        std::tm local{};
        localtime_r(&now, &local);
        char stamp[24] = {0};
        std::strftime(stamp, sizeof(stamp), "%Y%m%d-%H%M%S", &local);
        stamp_ = stamp;
        const size_t n = pre_.size();
        for (size_t k = 0; k < n; ++k)
        {
            SpeedSample p = pre_[(pre_head_ + k) % n];
            p.t = -static_cast<float>(n - k) * kFsmDt;
            samples_.push_back(p);
        }
    }

    SpeedSample sample(isaaclab::ManagerBasedRLEnv * env) const
    {
        SpeedSample s;
        s.cmd_vx = isaaclab::g_keyboard_cmd[0];
        s.cmd_vy = isaaclab::g_keyboard_cmd[1];
        s.cmd_wz = isaaclab::g_keyboard_cmd[2];

        const auto & state = FSMState::lowstate->msg_;
        const auto & command = FSMState::lowcmd->msg_;
        for (int i = 0; i < 12; ++i)
        {
            const auto & motor = state.motor_state()[i];
            const auto & mc = command.motor_cmd()[i];
            s.q[i] = motor.q();
            s.dq[i] = motor.dq();
            s.tau_app[i] = motor.tau_est();
            s.tau_cmd[i] = mc.tau() + mc.kp() * (mc.q() - motor.q()) + mc.kd() * (mc.dq() - motor.dq());
        }

        const auto & imu = state.imu_state();
        for (int i = 0; i < 3; ++i) s.ang_vel_b[i] = imu.gyroscope()[i];
        const float * gravity = env->robot->data.projected_gravity_b.data();
        for (int i = 0; i < 3; ++i) s.gravity_b[i] = gravity[i];

        if (highstate_)
        {
            const auto & high = highstate_->msg_;
            for (int i = 0; i < 3; ++i) s.v_world[i] = high.velocity()[i];
            s.base_z = high.position()[2];
            const Eigen::Quaternionf quat(
                imu.quaternion()[0], imu.quaternion()[1], imu.quaternion()[2], imu.quaternion()[3]);
            const Eigen::Vector3f v_body =
                quat.conjugate() * Eigen::Vector3f(s.v_world[0], s.v_world[1], s.v_world[2]);
            s.v_fwd = v_body.x();
            s.v_horiz = std::hypot(s.v_world[0], s.v_world[1]);
        }
        return s;
    }

    void write()
    {
        capturing_ = false;
        if (samples_.empty()) return;

        const std::string path = "speed_" + std::to_string(index_++) + "_" + stamp_ + ".csv";
        std::ofstream out(path, std::ios::out | std::ios::trunc);
        if (!out)
        {
            spdlog::warn("State_RLBase: could not open {} for the speed capture", path);
            samples_.clear();
            return;
        }

        out << "t,cmd_vx,cmd_vy,cmd_wz,v_fwd,v_horiz,vx_w,vy_w,vz_w,base_z,gx,gy,gz,wx,wy,wz";
        for (int i = 0; i < 12; ++i) out << "," << kJointNames[i] << "_q";
        for (int i = 0; i < 12; ++i) out << "," << kJointNames[i] << "_dq";
        for (int i = 0; i < 12; ++i) out << "," << kJointNames[i] << "_tau_cmd";
        for (int i = 0; i < 12; ++i) out << "," << kJointNames[i] << "_tau_app";
        out << "\n";

        float v_peak = 0.0f;
        float t_peak = 0.0f;
        for (const auto & s : samples_)
        {
            if (s.v_fwd > v_peak)
            {
                v_peak = s.v_fwd;
                t_peak = s.t;
            }
            out << s.t << "," << s.cmd_vx << "," << s.cmd_vy << "," << s.cmd_wz << "," << s.v_fwd
                << "," << s.v_horiz << "," << s.v_world[0] << "," << s.v_world[1] << ","
                << s.v_world[2] << "," << s.base_z << "," << s.gravity_b[0] << "," << s.gravity_b[1]
                << "," << s.gravity_b[2] << "," << s.ang_vel_b[0] << "," << s.ang_vel_b[1] << ","
                << s.ang_vel_b[2];
            for (int i = 0; i < 12; ++i) out << "," << s.q[i];
            for (int i = 0; i < 12; ++i) out << "," << s.dq[i];
            for (int i = 0; i < 12; ++i) out << "," << s.tau_cmd[i];
            for (int i = 0; i < 12; ++i) out << "," << s.tau_app[i];
            out << "\n";
        }
        spdlog::info(
            "State_RLBase: wrote {} -- {} samples over {:.2f}s, peak forward speed {:.2f} m/s at "
            "t={:.2f}s",
            path, samples_.size(), elapsed_, v_peak, t_peak);
        samples_.clear();
    }

    bool enabled_ = false;
    float pre_s_ = 0.5f;
    float max_s_ = 30.0f;
    float stop_speed_ = 0.2f;   // m/s, below which the robot counts as stopped
    float stop_hold_s_ = 0.3f;  // how long that has to hold before the capture closes
    float trigger_cmd_ = 0.1f;  // commanded forward speed that opens a capture

    std::shared_ptr<unitree::robot::go2::subscription::SportModeState> highstate_;
    std::vector<SpeedSample> pre_;
    size_t pre_head_ = 0;
    std::vector<SpeedSample> samples_;
    bool capturing_ = false;
    std::string stamp_;
    float elapsed_ = 0.0f;
    float stop_held_ = 0.0f;
    int index_ = 0;
};

SpeedCapture g_speed_capture;
} // namespace

State_RLBase::State_RLBase(int state_mode, std::string state_string)
: FSMState(state_mode, state_string) 
{
    auto cfg = param::config["FSM"][state_string];
    auto policy_dir = param::parser_policy_dir(cfg["policy_dir"].as<std::string>());

    env = std::make_unique<isaaclab::ManagerBasedRLEnv>(
        YAML::LoadFile(policy_dir / "params" / "deploy.yaml"),
        std::make_shared<unitree::BaseArticulation<LowState_t::SharedPtr>>(FSMState::lowstate)
    );
    env->alg = std::make_unique<isaaclab::OrtRunner>(policy_dir / "exported" / "policy.onnx");

    this->registered_checks.emplace_back(
        std::make_pair(
            [&]()->bool{ return isaaclab::mdp::bad_orientation(env.get(), 1.0); },
            FSMStringMap.right.at("Passive")
        )
    );

    // Operator overrides for keyboard driving; see the note above keyboard_velocity_commands.
    if (cfg["keyboard_vel_scale"])
    {
        isaaclab::g_keyboard_vel_scale = cfg["keyboard_vel_scale"].as<float>();
        spdlog::info("State_{}: keyboard_vel_scale {} (from config.yaml)",
                     state_string, *isaaclab::g_keyboard_vel_scale);
    }
    if (cfg["keyboard_alpha"])
    {
        isaaclab::g_keyboard_alpha = cfg["keyboard_alpha"].as<float>();
        spdlog::info("State_{}: keyboard_alpha {} (from config.yaml)",
                     state_string, *isaaclab::g_keyboard_alpha);
    }

    g_speed_capture.configure(cfg, state_string);
}

void State_RLBase::run()
{
    auto action = env->action_manager->processed_actions();
    for(int i(0); i < env->robot->data.joint_ids_map.size(); i++) {
        lowcmd->msg_.motor_cmd()[env->robot->data.joint_ids_map[i]].q() = action[i];
    }

    // After the q targets are written, so tau_cmd pairs the position command actually sent this
    // tick with the state it was evaluated against -- the same ordering the MuJoCo bridge uses.
    g_speed_capture.tick(env.get());
}
